<html>
	<body>
		<h1>Forum</h1>
		<form action="/forum/add" method="post">
			Ajouter un forum : <input type="text" name="title" /> <input type="submit" value="Ajouter" />
		</form>
		
		<h2>Listes des forums :</h2>
		<ul>
			<?php

foreach ($forums as $id => $forum) {
    ?>
			<li><a href="/forum/show?id=<?php
    
echo $id?>"><?php
    
echo $forum->getTitle()?></a>
			<?php

}
?>
		</ul>
	</body>
</html>
